/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.Vista;

/**
 *
 * @author terro
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        book = new javax.swing.JMenu();
        AddBook = new javax.swing.JMenuItem();
        ListBook = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddClient = new javax.swing.JMenuItem();
        ListClient = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        book.setText("Add libros");

        AddBook.setText("Crear");
        AddBook.setActionCommand("addBook");
        book.add(AddBook);
        AddBook.getAccessibleContext().setAccessibleName("AddBook");

        ListBook.setText("Listar");
        ListBook.setActionCommand("listBook");
        book.add(ListBook);

        jMenuBar1.add(book);

        jMenu2.setText("Add socios");

        AddClient.setText("Crear");
        AddClient.setActionCommand("addClient");
        jMenu2.add(AddClient);

        ListClient.setText("Listar");
        ListClient.setActionCommand("ListClient");
        jMenu2.add(ListClient);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem AddBook;
    public javax.swing.JMenuItem AddClient;
    public javax.swing.JMenuItem ListBook;
    public javax.swing.JMenuItem ListClient;
    private javax.swing.JMenu book;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
